- test6/frontend/src/source/MainSource.js
- test6/frontend/src/util/APIUtils.js
> 즐겨찾기 Utils에 메소드 추가

- test6/frontend/src/App.js
- test6/frontend/src/board/Board.js
- test6/frontend/src/menu/after/AfterLogin.js
프로그램실행시 isLogin를 false로 초기화 시켜줌
> 실행시 로그인 문제 해결

- test6/frontend/src/App.js
- test6/frontend/src/constants/index.js
- test6/frontend/src/menu/before/BeforeMenu.js
- test6/frontend/src/menu/before/BeforeMenu.scss
> BeforeMenu 메뉴 창 디자인 완료

- test6/frontend/src/App.js
- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/menu/before/BeforeMenu.js
- test6/frontend/src/menu/before/Description.js
> 메인 메뉴 디자인 초안

- test6/frontend/node_modules/@babel/core/lib/tools/build-external-helpers.js
- test6/frontend/node_modules/@babel/core/package.json
- test6/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/built-in-definitions.js
- test6/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- test6/frontend/node_modules/@babel/preset-env/package.json
- test6/frontend/src/menu/before/BeforeLogin.js
- test6/frontend/src/menu/before/BeforeLogin.scss
- test6/frontend/src/source/Source.js
- test6/frontend/src/source/Source.scss
- test6/frontend/yarn.lock
1. 홈페이지, 소스 선택 페이지 레이아웃 버그 수정
2. 위의 2개 페이지 하단에 Footer 추가
> 레이아웃 버그 수정

- test6/frontend/src/sign/signup/SignUpForm.js
- test6/frontend/src/sign/signup/SignUpForm.scss
> 회원가입 유효성 검사

- test6/frontend/src/App.js
- test6/frontend/yarn.lock
> Sign up 수정

- test6/frontend/src/mypage/DeleteUser.js
- test6/frontend/src/mypage/MyData.js
- test6/frontend/src/sign/login/LoginForm.js
- test6/frontend/src/sign/login/change/ChangePassword.js
- test6/frontend/src/sign/login/change/ChangePassword.scss
- test6/frontend/src/sign/signup/SignUpForm.js
- test6/frontend/src/sign/signup/SignUpForm.scss
1. 회원가입
- onBlur(포커스 벗어날때)일 때, 유효성 검사
2. 비밀번호 & 비밀번호 확인 버그 수정
> 기능 추가 및 버그 수정

- test6/frontend/package-lock.json
- test6/frontend/package.json
- test6/frontend/src/menu/after/favorite_main_page/FavoriteList.scss
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.js
> 즐겨찾기 게시판 오류 고치는 중

- test6/frontend/src/menu/after/AfterMenu.js
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.js
> 로그인 후 메뉴 변경

- test6/frontend/src/source/detail/DetailContents.js
- test6/frontend/src/source/detail/DetailMain.js
- test6/src/main/java/com/kosm/test6/controller/WebCrawler.java
> webCrawlwe

- test6/frontend/src/App.js
- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/util/APIUtils.js
- test6/src/main/java/com/kosm/test6/config/SecurityConfig.java
> 초기에 서버에서 리스트 받도록 설정

- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/sign/login/change/ChangePassword.js
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/versions_content/content_list/ContentList.js
> localStorage 에러 수정

- test6/frontend/src/source/detail/DetailContents.js
- test6/frontend/src/source/detail/DetailContents.scss
- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/MainSource.scss
- test6/frontend/src/source/main_code/versions_after_login_title/AfterMainSource.js
> detail페이지 초안

- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/versions_content/MainContent.scss
> 디테일 페이지 스크롤

- test6/frontend/src/menu/SourceList.js
> 검색 기능 문제 해결

- test6/frontend/src/source/main_code/MainSource.js
> 즐겨찾기 버튼 수정

- test6/frontend/src/menu/after/AfterLogin.scss
- test6/frontend/src/menu/after/favorite_main_page/FavoriteList.js
- test6/frontend/src/menu/after/favorite_main_page/FavoriteList.scss
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.js
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.scss
> 메인 화면 스크롤 조정

- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/menu/SourceList.scss
- test6/frontend/src/menu/before/BeforeLogin.js
- test6/frontend/src/menu/before/BeforeMenu.js
- test6/frontend/src/source/detail/DetailContents.js
- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/detail/DetailMain.scss
> 데이터 받는 것 수정 중

- test6/frontend/src/menu/before/BeforeMenu.js
- test6/frontend/src/source/detail/DetailContents.js
- test6/frontend/src/source/detail/DetailContents.scss
- test6/frontend/src/source/detail/DetailMain.js
> score출력시키기 수정 중

- test6/frontend/package-lock.json
- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/menu/SourceList.scss
> 카테고리 버그 수정

- test6/frontend/src/constants/index.js
- test6/frontend/src/menu/Footer.js
- test6/frontend/src/menu/Footer.scss
- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/menu/after/AfterMenu.js
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.js
- test6/frontend/src/source/detail/DetailContents.js
- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/versions_after_login_title/AfterMainSource.js
- test6/frontend/src/source/main_code/versions_content/content_list/ContentList.js
- 검색창 대소문자 버그 수정
- 콘솔로그 경고문 삭제
- Footer 높이 조절
> 디버깅 및 코드정리

- test6/frontend/src/source/main_code/MainSource.js
> 즐겨찾기 버그 수정

- test6/frontend/src/menu/after/favorite_main_page/FavoriteList.js
- test6/frontend/src/menu/after/favorite_main_page/FavoriteList.scss
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.js
- test6/frontend/src/source/detail/DetailMain.scss
- test6/frontend/src/source/main_code/MainSource.js
> 메인 화면 버그 수정

- test6/frontend/src/board/Article.js
- test6/frontend/src/board/Write.js
- test6/frontend/src/board/Write.scss
- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/detail/DetailMain.scss
- test6/frontend/src/source/main_code/MainSource.js
> 디버깅 및 기능 추가

- test6/frontend/src/source/main_code/MainSource.js
> 페이지 버튼 디버깅

- test6/frontend/package-lock.json
- test6/frontend/src/source/Source.scss
- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/MainSource.scss
- test6/frontend/src/source/main_code/versions_after_login_title/AfterMainSource.scss
- test6/src/main/java/com/kosm/test6/component/Scheduling.java
- test6/src/main/java/com/kosm/test6/controller/WebCrawler.java
> MainSource 제목 추가

- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/detail/DetailMain.scss
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/MainSource.scss
- test6/src/main/java/com/kosm/test6/controller/AuthController.java
> score sorting버튼 추가

- test6/frontend/package-lock.json
- test6/frontend/src/menu/Footer.js
- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/detail/DetailMain.scss
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/MainSource.scss
- test6/frontend/yarn.lock
- test6/src/main/java/com/kosm/test6/component/Scheduling.java
- test6/src/main/java/com/kosm/test6/controller/AuthController.java
- test6/src/main/java/com/kosm/test6/controller/WebCrawler.java
- test6/src/main/java/com/kosm/test6/model/OpenSource.java
https://github.com/0420syj/kosm/commit/7e6b207eaa9659226cb7a2effd3a772f2d6fb49f
이 상태로 백업. revert 할껄그랬나
> 깃허브 폭발 전으로 백업

- test6/frontend/package-lock.json
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/versions_content/content_list/ContentList.js
- test6/frontend/src/util/APIUtils.js
- test6/src/main/java/com/kosm/test6/component/Scheduling.java
> 버전 정렬 수정 중

- test6/frontend/src/source/detail/DetailContents.js
- test6/frontend/src/source/detail/DetailContents.scss
- test6/frontend/src/source/detail/DetailMain.js
- test6/frontend/src/source/main_code/MainSource.js
- test6/frontend/src/source/main_code/versions_content/MainContent.js
> 20개씩 나오게 하기

- test6/frontend/src/menu/after/favorite_main_page/Favorite.js
- test6/frontend/src/sign/login/LoginForm.js
- test6/frontend/src/util/APIAdmin.js
- test6/src/main/java/com/kosm/test6/controller/AuthController.java
> sessionStorage수정

- test6/frontend/src/data/OpenSourceData.js
- test6/frontend/src/menu/SourceList.js
> category생성

- test6/frontend/src/menu/SourceList.js
- test6/frontend/src/menu/after/favorite_main_page/FavoriteList.js
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.js
- test6/frontend/src/menu/after/favorite_main_page/MainFavorite.scss
- test6/src/main/java/com/kosm/test6/component/Scheduling.java
- test6/src/main/java/com/kosm/test6/payload/ProjectListResponse.java
> 즐겨찾기 화면 수정
